version: "3.8"

services:
  app:
    build: .
    container_name: lunch-menu-api
    ports:
      - "8137:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
    restart: unless-stopped 